###
GET http://localhost:5005

###
POST http://localhost:5005/auth/register
Content-Type: application/json

{
    "username":"naseef@gmail.com",
    "password":"123123123"
}

###
POST http://localhost:5005/auth/login
Content-Type: application/json

{
    "username":"naseef@gmail.com",
    "password":"123123123"
}

###
GET http://localhost:5005/urls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNzgzYTBiMDY1NDk1ZmUxZWUzMzdiYyIsImlhdCI6MTc4NjI2NTA1NiwiZXhwIjoxNzg2MzUxNDU2fQ.k-KagHbDG1ZRoREDlHerweReKBW8RzI-ZuQfgPHtUEg
Content-Type: application/json

###
POST http://localhost:5005/urls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNzgzYTBiMDY1NDk1ZmUxZWUzMzdiYyIsImlhdCI6MTc4NjI2NTA1NiwiZXhwIjoxNzg2MzUxNDU2fQ.k-KagHbDG1ZRoREDlHerweReKBW8RzI-ZuQfgPHtUEg
Content-Type: application/json

{
    "originalUrl":"https://www.googole.com"
}
